version: '2'

services:
  ci-build:
    image: mcr.microsoft.com/dotnet/core/aspnet:3.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore **/*.csproj && dotnet publish **/*.csproj -c Release -o ./obj/Docker/publish"
