version: '2'

services:
  ci-build:
    image: mcr.microsoft.com/dotnet/core/aspnet:3.1
    volumes:
      - .:/ContainerWebApp
    working_dir: /ContainerWebApp
    command: /bin/bash -c "dotnet restore ./ContainerWebApp.sln && dotnet publish ./ContainerWebApp.sln -c Release -o ./obj/Docker/publish"
